<?php
/**
 * Created by PhpStorm.
 * User: lkx
 * Date: 2018/5/2
 * Time: 15:42
 */
namespace api\controllers;
use yii\rest\ActiveController;

class UserController extends ActiveController{
	public $modelClass = 'common\models\User';
	public function actions()
	{
		$action= parent::actions(); // TODO: Change the autogenerated stub
		unset($action['index']);
		unset($action['create']);
		unset($action['update']);
		unset($action['delete']);
	}

	public function actionIndex()
	{
		return ['111','222'];
	}
	public function actionTest(){
		echo '222';
	}
}